version: 2.1
            
jobs:

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Promoto to prod
          command: |
            aws cloudformation deploy \
              --template-file cloudfront.yml \
              --stack-name production-distro \
              --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"


  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create bucket
          command: |
            aws cloudformation deploy \
              --template-file bucket.yml \
              --stack-name createnewS3bucket \
              --parameter-overrides NAME="${CIRCLE_WORKFLOW_ID:0:7}" 
      - run: aws s3 sync s3://abs3bucket1 s3://"${CIRCLE_WORKFLOW_ID:0:7}" --delete
 
workflows:
    default:
      jobs:
        - create_and_deploy_front_end
        - promote_to_production:
                       requires: 
                          - create_and_deploy_front_end
